### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by CallmeZhangChenchen** [jwfromm/Riptide#5]
git clone --recursive git@github.com:jwfromm/riptide.git
是不是应该是这样
git clone --recursive https://@github.com:jwfromm/riptide.git

cd Riptide/tvm && mkdir build && cp cmake/config.cmake build && cd build
cmake ..
make -j4
export TVM_HOME={RiptideLocation}/tvm
export PYTHONPATH=$TVM_HOME/python:$TVM_HOME/topi/python:$PYTHONPATH
这一步成功，succeful....

You should now be able to import Riptide in Python and are ready to train and deploy a binary model!
不，我不行，no I can't , import Riptide erro .

**Comment by jwfromm** [comment]
can you be a little more specific on what error you're getting? If you set your pythonpath up correctly `import riptide` should work fine. You can test importing riptide while in the `Riptide` directory to make sure that works.
