### ISSUE TITLE
Binary Convolution

### ISSUE THREAD

**Issue by PatrickAnnie** [jwfromm/Riptide#8]
Hi, 

I've trained a binary model using alexnet, and I'm wondering that if binary convolution uses xnor-popcount operation to replace floating point multiply-accumulate in training phase or just in pure inference phase?

Another question is that I look into bitserial_conv2d.py in Riptide/tvm/topi/python/topi/x86:

```python
def _conv(n, co, h, w, vh, vw, vc):
        b1b2 = (b1+b2).astype(out_dtype)
        if unipolar:
            return tvm.sum((tvm.popcount(
                data_vec[n, h, w, ci, vh*HSTR+dh, vw*WSTR+dw, b1].astype(out_dtype) &
                kernel_vec[co, ci, dh, dw, b2, vc].astype(out_dtype))  -
                            tvm.popcount(
                                data_vec[n, h, w, ci, vh*HSTR+dh, vw*WSTR+dw, b1].astype(out_dtype)
                                & ~kernel_vec[co, ci, dh, dw, b2, vc]).astype(out_dtype)) << b1b2,
                           axis=[ci, dh, dw, b1, b2])

        return tvm.sum((tvm.popcount(
            data_vec[n, h, w, ci, vh*HSTR+dh, vw*WSTR+dw, b1] &
            kernel_vec[co, ci, dh, dw, b2, vc])).astype(out_dtype) << b1b2,
                       axis=[ci, dh, dw, b1, b2])
```
I found that bipolar quantization allows xnor-popcount operation to replace floating point multiply-accumulate in the paper Riptide, but it is and-popcount operation in this file.

Why there is a difference? Or I reference a wrong file?

**Comment by jwfromm** [comment]
Hello,

Thanks for your interest in Riptide! We only use TVM during inference. At training time all binary ops are simulated in tensorflow, so there is no xnor-popcount being applied.

You're right about xnor-popcount missing from that topi definition. The non-unipolar case there isn't actually quite bipolar, its when both weights and activations represent values in [0, 1], whereas the case listed unipolar is for when activations represent values in [0, 1] and weights represent values in [-1, 1]. Although we discuss the alternative case where both activations and weights represent [-1, 1] in our paper, it is computationally equivalent to the [0, 1] and would only require changing the and operation for an xnor.

**Comment by PatrickAnnie** [comment]
Hi,

So, the computational behavior is the same although operations used are different, right?
Thanks for your reply!
